# Site settings
title: TecnoPaineis
email: contato@tecnopaineis.com.br
description: ""
baseurl: ""
url: "http://tecnopaineis.com.br"

# Build settings
markdown: kramdown
permalink: pretty

#sass settings
sass:
  sass_dir: assets/stylesheets/_sass

#ignore files
exclude: ["vendor/cache", "Guardfile", 'Gemfile', 'Gemfile.lock']

#collections
collections:
  cases:
    output: true